# Generated by Django 2.2.5 on 2022-03-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='takencourse',
            field=models.CharField(blank=True, choices=[('bigdata', 'BIGDATA'), ('ai', 'AI'), ('cloud', 'CLOUD'), ('iot', 'IOT')], max_length=20, null=True),
        ),
    ]
