# Generated by Django 2.2.5 on 2022-03-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220307_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
