# Generated by Django 2.2.5 on 2022-03-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='category',
            field=models.CharField(choices=[('Cafe', 'Cafe'), ('FOOD', 'Food'), ('NOTEBOOK', 'Notebook')], max_length=20),
        ),
    ]
