# Generated by Django 2.2.5 on 2022-03-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('before', '모집중'), ('start', '도전시작'), ('finish', '도전종료')], default='before', max_length=8)),
                ('routine', models.CharField(choices=[('everyday', '매일'), ('weekend_only', '주말만'), ('5times_a_week', '월화수목금'), ('3times_a_week', '주3회'), ('twice_a_week', '주2회'), ('once_a_week', '주1회')], default='everyday', max_length=15)),
                ('num_of_auth_per_day', models.IntegerField(default=1)),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('created', models.DateField()),
                ('modified', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
