# Generated by Django 2.2.5 on 2022-03-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=150)),
                ('file', models.ImageField(upload_to='challenge_photo')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfauth', to='challenges.Challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
